-- ============================================================
-- RAPID Repair System — Oracle DDL for SQL Developer Data Modeler
-- Import: File > Import > DDL File
--          Select Site: Oracle Database 21c
--          File: this file
-- ============================================================

CREATE TABLE users (
  id            NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  role          VARCHAR2(20)  NOT NULL,
  first_name    VARCHAR2(100) NOT NULL,
  last_name     VARCHAR2(100) NOT NULL,
  email         VARCHAR2(190) NOT NULL,
  phone         VARCHAR2(30),
  password      VARCHAR2(255) NOT NULL,
  status        VARCHAR2(10)  DEFAULT 'active' NOT NULL,
  created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT ck_users_role CHECK (role IN ('admin', 'technician', 'customer')),
  CONSTRAINT ck_users_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE customers (
  id            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id       NUMBER(10) NOT NULL,
  address       CLOB,
  created_at    TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at    TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_customers PRIMARY KEY (id),
  CONSTRAINT uq_customers_user UNIQUE (user_id),
  CONSTRAINT fk_customers_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE technicians (
  id                   NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id              NUMBER(10)    NOT NULL,
  specialization       VARCHAR2(150),
  availability_status  VARCHAR2(20)  DEFAULT 'available' NOT NULL,
  created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_technicians PRIMARY KEY (id),
  CONSTRAINT uq_technicians_user UNIQUE (user_id),
  CONSTRAINT ck_tech_availability CHECK (availability_status IN ('available', 'busy', 'unavailable')),
  CONSTRAINT fk_technicians_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE devices (
  id                  NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id         NUMBER(10)    NOT NULL,
  device_type         VARCHAR2(100) NOT NULL,
  brand               VARCHAR2(100) NOT NULL,
  model               VARCHAR2(150) NOT NULL,
  serial_number       VARCHAR2(150),
  imei                VARCHAR2(50),
  color               VARCHAR2(50),
  accessories         CLOB,
  physical_condition  CLOB,
  created_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_devices PRIMARY KEY (id),
  CONSTRAINT fk_devices_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

CREATE TABLE repair_tickets (
  id                      NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ticket_number           VARCHAR2(30)  NOT NULL,
  customer_id             NUMBER(10)    NOT NULL,
  device_id               NUMBER(10)    NOT NULL,
  assigned_technician_id  NUMBER(10),
  problem_description     CLOB          NOT NULL,
  current_status          VARCHAR2(30)  DEFAULT 'booking_submitted' NOT NULL,
  priority                VARCHAR2(10)  DEFAULT 'normal' NOT NULL,
  appointment_date        TIMESTAMP,
  received_at             TIMESTAMP,
  completed_at            TIMESTAMP,
  estimated_completion    TIMESTAMP,
  created_at              TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at              TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_repair_tickets PRIMARY KEY (id),
  CONSTRAINT uq_tickets_number UNIQUE (ticket_number),
  CONSTRAINT ck_tickets_status CHECK (current_status IN (
    'booking_submitted', 'received', 'diagnosing', 'quotation_pending',
    'awaiting_approval', 'approved', 'repairing', 'ready_for_pickup',
    'completed', 'declined', 'cancelled'
  )),
  CONSTRAINT ck_tickets_priority CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  CONSTRAINT fk_tickets_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
  CONSTRAINT fk_tickets_device FOREIGN KEY (device_id) REFERENCES devices (id),
  CONSTRAINT fk_tickets_technician FOREIGN KEY (assigned_technician_id) REFERENCES technicians (id) ON DELETE SET NULL
);

CREATE TABLE device_media (
  id              NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ticket_id       NUMBER(10)    NOT NULL,
  uploaded_by     NUMBER(10)    NOT NULL,
  file_name       VARCHAR2(255) NOT NULL,
  file_path       VARCHAR2(500) NOT NULL,
  file_type       VARCHAR2(100) NOT NULL,
  media_category  VARCHAR2(20)  DEFAULT 'before_repair' NOT NULL,
  uploaded_at     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_device_media PRIMARY KEY (id),
  CONSTRAINT ck_media_category CHECK (media_category IN ('before_repair', 'diagnosis', 'during_repair', 'after_repair')),
  CONSTRAINT fk_media_ticket FOREIGN KEY (ticket_id) REFERENCES repair_tickets (id) ON DELETE CASCADE,
  CONSTRAINT fk_media_uploader FOREIGN KEY (uploaded_by) REFERENCES users (id)
);

CREATE TABLE diagnoses (
  id                    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ticket_id             NUMBER(10) NOT NULL,
  technician_id         NUMBER(10) NOT NULL,
  diagnosis             CLOB       NOT NULL,
  recommended_action    CLOB,
  estimated_completion  TIMESTAMP,
  created_at            TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at            TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_diagnoses PRIMARY KEY (id),
  CONSTRAINT fk_diagnoses_ticket FOREIGN KEY (ticket_id) REFERENCES repair_tickets (id) ON DELETE CASCADE,
  CONSTRAINT fk_diagnoses_technician FOREIGN KEY (technician_id) REFERENCES technicians (id)
);

CREATE TABLE ai_suggestions (
  id            NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ticket_id     NUMBER(10)   NOT NULL,
  kind          VARCHAR2(40) DEFAULT 'technician_repair' NOT NULL,
  context_hash  CHAR(64)     NOT NULL,
  payload_json  CLOB         NOT NULL,
  created_at    TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at    TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_ai_suggestions PRIMARY KEY (id),
  CONSTRAINT uq_ai_ticket_kind UNIQUE (ticket_id, kind),
  CONSTRAINT fk_ai_ticket FOREIGN KEY (ticket_id) REFERENCES repair_tickets (id) ON DELETE CASCADE
);

CREATE TABLE quotations (
  id              NUMBER(10)     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ticket_id       NUMBER(10)     NOT NULL,
  technician_id   NUMBER(10)     NOT NULL,
  labor_cost      NUMBER(10,2)   DEFAULT 0 NOT NULL,
  parts_cost      NUMBER(10,2)   DEFAULT 0 NOT NULL,
  other_cost      NUMBER(10,2)   DEFAULT 0 NOT NULL,
  total_amount    NUMBER(10,2)   DEFAULT 0 NOT NULL,
  notes           CLOB,
  status          VARCHAR2(10)   DEFAULT 'pending' NOT NULL,
  valid_until     DATE,
  created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_quotations PRIMARY KEY (id),
  CONSTRAINT ck_quotations_status CHECK (status IN ('pending', 'approved', 'declined', 'expired')),
  CONSTRAINT fk_quotations_ticket FOREIGN KEY (ticket_id) REFERENCES repair_tickets (id) ON DELETE CASCADE,
  CONSTRAINT fk_quotations_technician FOREIGN KEY (technician_id) REFERENCES technicians (id)
);

CREATE TABLE repair_status_history (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ticket_id   NUMBER(10)    NOT NULL,
  status      VARCHAR2(30)  NOT NULL,
  remarks     CLOB,
  updated_by  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_repair_status_history PRIMARY KEY (id),
  CONSTRAINT ck_status_history CHECK (status IN (
    'booking_submitted', 'received', 'diagnosing', 'quotation_pending',
    'awaiting_approval', 'approved', 'repairing', 'ready_for_pickup',
    'completed', 'declined', 'cancelled'
  )),
  CONSTRAINT fk_status_history_ticket FOREIGN KEY (ticket_id) REFERENCES repair_tickets (id) ON DELETE CASCADE,
  CONSTRAINT fk_status_history_user FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE warranties (
  id               NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ticket_id        NUMBER(10)    NOT NULL,
  warranty_start   DATE          NOT NULL,
  warranty_end     DATE          NOT NULL,
  warranty_days    NUMBER(10)    DEFAULT 30 NOT NULL,
  warranty_status  VARCHAR2(20)  DEFAULT 'active' NOT NULL,
  created_at       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_warranties PRIMARY KEY (id),
  CONSTRAINT uq_warranties_ticket UNIQUE (ticket_id),
  CONSTRAINT ck_warranty_status CHECK (warranty_status IN ('active', 'expiring_soon', 'expired')),
  CONSTRAINT fk_warranties_ticket FOREIGN KEY (ticket_id) REFERENCES repair_tickets (id) ON DELETE CASCADE
);

CREATE TABLE warranty_claims (
  id                  NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  original_ticket_id  NUMBER(10)    NOT NULL,
  customer_id         NUMBER(10)    NOT NULL,
  device_id           NUMBER(10)    NOT NULL,
  issue_description   CLOB          NOT NULL,
  claim_status        VARCHAR2(20)  DEFAULT 'submitted' NOT NULL,
  technician_id       NUMBER(10),
  resolution          CLOB,
  created_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_warranty_claims PRIMARY KEY (id),
  CONSTRAINT ck_claim_status CHECK (claim_status IN ('submitted', 'reviewing', 'approved', 'rejected', 'repairing', 'resolved')),
  CONSTRAINT fk_claims_ticket FOREIGN KEY (original_ticket_id) REFERENCES repair_tickets (id),
  CONSTRAINT fk_claims_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
  CONSTRAINT fk_claims_device FOREIGN KEY (device_id) REFERENCES devices (id),
  CONSTRAINT fk_claims_technician FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE SET NULL
);

CREATE TABLE notifications (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id     NUMBER(10)    NOT NULL,
  ticket_id   NUMBER(10),
  title       VARCHAR2(200) NOT NULL,
  message     CLOB          NOT NULL,
  is_read     NUMBER(1)     DEFAULT 0 NOT NULL,
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_notifications PRIMARY KEY (id),
  CONSTRAINT ck_notifications_read CHECK (is_read IN (0, 1)),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_notifications_ticket FOREIGN KEY (ticket_id) REFERENCES repair_tickets (id) ON DELETE SET NULL
);

CREATE TABLE activity_logs (
  id           NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id      NUMBER(10),
  action       VARCHAR2(100) NOT NULL,
  description  CLOB,
  ip_address   VARCHAR2(45),
  created_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_activity_logs PRIMARY KEY (id),
  CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE system_settings (
  id             NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  setting_key    VARCHAR2(100) NOT NULL,
  setting_value  CLOB,
  updated_at     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_system_settings PRIMARY KEY (id),
  CONSTRAINT uq_settings_key UNIQUE (setting_key)
);

COMMENT ON TABLE users IS 'Login accounts for administrators, technicians, and customers';
COMMENT ON COLUMN users.id IS 'Unique ID of the user';
COMMENT ON COLUMN users.role IS 'Role of the user in the RAPID system';
COMMENT ON COLUMN users.first_name IS 'First name of the user';
COMMENT ON COLUMN users.last_name IS 'Last name of the user';
COMMENT ON COLUMN users.email IS 'Email address used to log in';
COMMENT ON COLUMN users.phone IS 'Contact number of the user';
COMMENT ON COLUMN users.password IS 'Hashed password of the user';
COMMENT ON COLUMN users.status IS 'Account status of the user';
COMMENT ON COLUMN users.created_at IS 'Date and time the user was created';
COMMENT ON COLUMN users.updated_at IS 'Date and time the user was last updated';

COMMENT ON TABLE customers IS 'Customer profile linked to a user account';
COMMENT ON COLUMN customers.id IS 'Unique ID of the customer';
COMMENT ON COLUMN customers.user_id IS 'Linked user account of the customer';
COMMENT ON COLUMN customers.address IS 'Address of the customer';
COMMENT ON COLUMN customers.created_at IS 'Date and time the customer was created';
COMMENT ON COLUMN customers.updated_at IS 'Date and time the customer was last updated';

COMMENT ON TABLE technicians IS 'Technician profile linked to a user account';
COMMENT ON COLUMN technicians.id IS 'Unique ID of the technician';
COMMENT ON COLUMN technicians.user_id IS 'Linked user account of the technician';
COMMENT ON COLUMN technicians.specialization IS 'Repair specialization of the technician';
COMMENT ON COLUMN technicians.availability_status IS 'Current availability of the technician';
COMMENT ON COLUMN technicians.created_at IS 'Date and time the technician was created';
COMMENT ON COLUMN technicians.updated_at IS 'Date and time the technician was last updated';

COMMENT ON TABLE devices IS 'Customer devices submitted for repair';
COMMENT ON COLUMN devices.id IS 'Unique ID of the device';
COMMENT ON COLUMN devices.customer_id IS 'Owner of the device';
COMMENT ON COLUMN devices.device_type IS 'Type of the device';
COMMENT ON COLUMN devices.brand IS 'Brand of the device';
COMMENT ON COLUMN devices.model IS 'Model of the device';
COMMENT ON COLUMN devices.serial_number IS 'Serial number of the device';
COMMENT ON COLUMN devices.imei IS 'IMEI of the device';
COMMENT ON COLUMN devices.color IS 'Color of the device';
COMMENT ON COLUMN devices.accessories IS 'Accessories received with the device';
COMMENT ON COLUMN devices.physical_condition IS 'Physical condition of the device';
COMMENT ON COLUMN devices.created_at IS 'Date and time the device was created';
COMMENT ON COLUMN devices.updated_at IS 'Date and time the device was last updated';

COMMENT ON TABLE repair_tickets IS 'Central repair job record for a customer device';
COMMENT ON COLUMN repair_tickets.id IS 'Unique ID of the repair ticket';
COMMENT ON COLUMN repair_tickets.ticket_number IS 'Public tracking number of the ticket';
COMMENT ON COLUMN repair_tickets.customer_id IS 'Customer who requested the repair';
COMMENT ON COLUMN repair_tickets.device_id IS 'Device attached to the ticket';
COMMENT ON COLUMN repair_tickets.assigned_technician_id IS 'Technician assigned to the ticket';
COMMENT ON COLUMN repair_tickets.problem_description IS 'Reported problem of the device';
COMMENT ON COLUMN repair_tickets.current_status IS 'Current repair status of the ticket';
COMMENT ON COLUMN repair_tickets.priority IS 'Priority level of the ticket';
COMMENT ON COLUMN repair_tickets.appointment_date IS 'Scheduled appointment date of the ticket';
COMMENT ON COLUMN repair_tickets.received_at IS 'Date and time the device was received';
COMMENT ON COLUMN repair_tickets.completed_at IS 'Date and time the repair was completed';
COMMENT ON COLUMN repair_tickets.estimated_completion IS 'Estimated completion date of the repair';
COMMENT ON COLUMN repair_tickets.created_at IS 'Date and time the ticket was created';
COMMENT ON COLUMN repair_tickets.updated_at IS 'Date and time the ticket was last updated';

COMMENT ON TABLE device_media IS 'Photos and files attached to a repair ticket';
COMMENT ON COLUMN device_media.id IS 'Unique ID of the media file';
COMMENT ON COLUMN device_media.ticket_id IS 'Repair ticket of the media file';
COMMENT ON COLUMN device_media.uploaded_by IS 'User who uploaded the media file';
COMMENT ON COLUMN device_media.file_name IS 'Original file name of the media';
COMMENT ON COLUMN device_media.file_path IS 'Stored path of the media file';
COMMENT ON COLUMN device_media.file_type IS 'MIME type of the media file';
COMMENT ON COLUMN device_media.media_category IS 'Stage of the repair when the media was taken';
COMMENT ON COLUMN device_media.uploaded_at IS 'Date and time the media was uploaded';

COMMENT ON TABLE diagnoses IS 'Technician diagnosis recorded for a repair ticket';
COMMENT ON COLUMN diagnoses.id IS 'Unique ID of the diagnosis';
COMMENT ON COLUMN diagnoses.ticket_id IS 'Repair ticket of the diagnosis';
COMMENT ON COLUMN diagnoses.technician_id IS 'Technician who recorded the diagnosis';
COMMENT ON COLUMN diagnoses.diagnosis IS 'Diagnosis findings of the device';
COMMENT ON COLUMN diagnoses.recommended_action IS 'Recommended repair action';
COMMENT ON COLUMN diagnoses.estimated_completion IS 'Estimated completion after diagnosis';
COMMENT ON COLUMN diagnoses.created_at IS 'Date and time the diagnosis was created';
COMMENT ON COLUMN diagnoses.updated_at IS 'Date and time the diagnosis was last updated';

COMMENT ON TABLE ai_suggestions IS 'Cached AI helper output for a repair ticket';
COMMENT ON COLUMN ai_suggestions.id IS 'Unique ID of the AI suggestion';
COMMENT ON COLUMN ai_suggestions.ticket_id IS 'Repair ticket of the AI suggestion';
COMMENT ON COLUMN ai_suggestions.kind IS 'Type of AI suggestion stored';
COMMENT ON COLUMN ai_suggestions.context_hash IS 'Hash of the ticket context used for cache';
COMMENT ON COLUMN ai_suggestions.payload_json IS 'JSON payload of the AI suggestion';
COMMENT ON COLUMN ai_suggestions.created_at IS 'Date and time the suggestion was created';
COMMENT ON COLUMN ai_suggestions.updated_at IS 'Date and time the suggestion was last updated';

COMMENT ON TABLE quotations IS 'Repair cost quotation for a ticket';
COMMENT ON COLUMN quotations.id IS 'Unique ID of the quotation';
COMMENT ON COLUMN quotations.ticket_id IS 'Repair ticket of the quotation';
COMMENT ON COLUMN quotations.technician_id IS 'Technician who prepared the quotation';
COMMENT ON COLUMN quotations.labor_cost IS 'Labor cost of the repair';
COMMENT ON COLUMN quotations.parts_cost IS 'Parts cost of the repair';
COMMENT ON COLUMN quotations.other_cost IS 'Other cost of the repair';
COMMENT ON COLUMN quotations.total_amount IS 'Total amount of the quotation';
COMMENT ON COLUMN quotations.notes IS 'Additional notes of the quotation';
COMMENT ON COLUMN quotations.status IS 'Approval status of the quotation';
COMMENT ON COLUMN quotations.valid_until IS 'Expiry date of the quotation';
COMMENT ON COLUMN quotations.created_at IS 'Date and time the quotation was created';
COMMENT ON COLUMN quotations.updated_at IS 'Date and time the quotation was last updated';

COMMENT ON TABLE repair_status_history IS 'Timeline of status changes for a repair ticket';
COMMENT ON COLUMN repair_status_history.id IS 'Unique ID of the status history record';
COMMENT ON COLUMN repair_status_history.ticket_id IS 'Repair ticket of the status change';
COMMENT ON COLUMN repair_status_history.status IS 'Status value recorded in the timeline';
COMMENT ON COLUMN repair_status_history.remarks IS 'Remarks of the status change';
COMMENT ON COLUMN repair_status_history.updated_by IS 'User who recorded the status change';
COMMENT ON COLUMN repair_status_history.created_at IS 'Date and time the status was recorded';

COMMENT ON TABLE warranties IS 'Warranty coverage issued after a completed repair';
COMMENT ON COLUMN warranties.id IS 'Unique ID of the warranty';
COMMENT ON COLUMN warranties.ticket_id IS 'Completed repair ticket of the warranty';
COMMENT ON COLUMN warranties.warranty_start IS 'Start date of the warranty';
COMMENT ON COLUMN warranties.warranty_end IS 'End date of the warranty';
COMMENT ON COLUMN warranties.warranty_days IS 'Coverage length of the warranty in days';
COMMENT ON COLUMN warranties.warranty_status IS 'Current status of the warranty';
COMMENT ON COLUMN warranties.created_at IS 'Date and time the warranty was created';
COMMENT ON COLUMN warranties.updated_at IS 'Date and time the warranty was last updated';

COMMENT ON TABLE warranty_claims IS 'Warranty claim filed against a previous repair';
COMMENT ON COLUMN warranty_claims.id IS 'Unique ID of the warranty claim';
COMMENT ON COLUMN warranty_claims.original_ticket_id IS 'Original repair ticket of the claim';
COMMENT ON COLUMN warranty_claims.customer_id IS 'Customer who filed the claim';
COMMENT ON COLUMN warranty_claims.device_id IS 'Device covered by the claim';
COMMENT ON COLUMN warranty_claims.issue_description IS 'Reported issue of the warranty claim';
COMMENT ON COLUMN warranty_claims.claim_status IS 'Current status of the warranty claim';
COMMENT ON COLUMN warranty_claims.technician_id IS 'Technician assigned to the claim';
COMMENT ON COLUMN warranty_claims.resolution IS 'Resolution notes of the claim';
COMMENT ON COLUMN warranty_claims.created_at IS 'Date and time the claim was created';
COMMENT ON COLUMN warranty_claims.updated_at IS 'Date and time the claim was last updated';

COMMENT ON TABLE notifications IS 'In-app notifications sent to users';
COMMENT ON COLUMN notifications.id IS 'Unique ID of the notification';
COMMENT ON COLUMN notifications.user_id IS 'User who receives the notification';
COMMENT ON COLUMN notifications.ticket_id IS 'Related repair ticket of the notification';
COMMENT ON COLUMN notifications.title IS 'Title of the notification';
COMMENT ON COLUMN notifications.message IS 'Message of the notification';
COMMENT ON COLUMN notifications.is_read IS 'Read flag of the notification';
COMMENT ON COLUMN notifications.created_at IS 'Date and time the notification was created';

COMMENT ON TABLE activity_logs IS 'Audit trail of user and system actions';
COMMENT ON COLUMN activity_logs.id IS 'Unique ID of the activity log';
COMMENT ON COLUMN activity_logs.user_id IS 'User who performed the action';
COMMENT ON COLUMN activity_logs.action IS 'Action name of the log';
COMMENT ON COLUMN activity_logs.description IS 'Details of the activity';
COMMENT ON COLUMN activity_logs.ip_address IS 'IP address of the activity';
COMMENT ON COLUMN activity_logs.created_at IS 'Date and time the activity was recorded';

COMMENT ON TABLE system_settings IS 'Key-value configuration of the RAPID system';
COMMENT ON COLUMN system_settings.id IS 'Unique ID of the setting';
COMMENT ON COLUMN system_settings.setting_key IS 'Key name of the setting';
COMMENT ON COLUMN system_settings.setting_value IS 'Value of the setting';
COMMENT ON COLUMN system_settings.updated_at IS 'Date and time the setting was last updated';
